### PR TITLE
feat: added Bungie provider

### PR DESCRIPTION
**Pull request by omznc**
Added the [Bungie.net](https://github.com/Bungie-net/api/wiki/OAuth-Documentation) provider (#100)

### CODE REVIEW

**Comment by pilcrowonpaper** [comment]
Please refactor the PR to use `oslo/oauth2` like the other providers

**Comment by omznc** [comment]
> Please refactor the PR to use `oslo/oauth2` like the other providers

@pilcrowOnPaper  I think that's that.

Sorry for the late reply, I wasn't subscribed to the thread for some reason.

**Review by SapphoSys — APPROVED** [review]

**Comment by SapphoSys** [comment]
bump! @pilcrowOnPaper any chance you could take a look?

would really love to have this as i'm developing a project that relies on bungie.net authentication. 
tested it out and i haven't had any issues so far.

thanks <3

**Comment by pilcrowonpaper** [comment]
Superseded by #170

**Pull request closed without merging**
